/*
 * readingList
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import "github.com/hertz-contrib/migrate/cmd/net/testdata/go-web/readingList/internal/data"

type BookEnvelope struct {
	Book *Book `json:"book,omitempty"`
}

func NewBookEnvelopeFromEntity(book *data.Book) *BookEnvelope {
	bookModel := NewBookModel(book)
	return &BookEnvelope{Book: bookModel}
}
