/*
 * readingList
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import "github.com/hertz-contrib/migrate/cmd/net/testdata/go-web/readingList/internal/data"

type Book struct {
	Id int64 `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Published int32 `json:"published,omitempty"`

	Pages int32 `json:"pages,omitempty"`

	Rating float32 `json:"rating,omitempty"`

	Genres []string `json:"genres,omitempty"`
}

func NewBookModel(book *data.Book) *Book {
	return &Book{
		Id:        book.ID,
		Title:     book.Title,
		Published: int32(book.Published),
		Pages:     int32(book.Pages),
		Rating:    float32(book.Rating),
		Genres:    book.Genres,
	}
}

func NewBooksModel(books []*data.Book) []*Book {
	var bookModels []*Book

	for _, book := range books {
		bookModel := NewBookModel(book)
		bookModels = append(bookModels, bookModel)
	}
	return bookModels
}
