# Typo check: https://github.com/crate-ci/typos

[files]
extend-exclude = ["go.sum", "check_branch_name.sh"]

[default.extend-identifiers]
# *sigh* this just isn't worth the cost of fixing
Referer = "Referer"
referer = "referer"
SetRefererBytes = "SetRefererBytes"
